<?php
namespace Database\Seeders;

use App\Models\Source;
use Illuminate\Database\Seeder;

class SourceSeeder extends Seeder
{
    public function run(): void
    {
        $sources = [
            // TÜRKİYE - Yandaş
            ['name' => 'TRT Haber', 'rss_url' => 'https://www.trthaber.com/sondakika.rss', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'Sabah', 'rss_url' => 'https://www.sabah.com.tr/rss/anasayfa.xml', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'A Haber', 'rss_url' => 'https://www.ahaber.com.tr/rss/anasayfa.xml', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'Star Gazetesi', 'rss_url' => 'https://www.star.com.tr/rss/', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'Türkiye Gazetesi', 'rss_url' => 'https://www.turkiyegazetesi.com.tr/rss.xml', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'Milliyet', 'rss_url' => 'https://www.milliyet.com.tr/rss/rssNew/sondakika.xml', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'Haber7', 'rss_url' => 'https://www.haber7.com/rss/', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'Haberturk', 'rss_url' => 'https://www.haberturk.com/rss/haberturk.xml', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'Takvim', 'rss_url' => 'https://www.takvim.com.tr/rss.xml', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            ['name' => 'Posta', 'rss_url' => 'https://www.posta.com.tr/rss/anasayfa.xml', 'country_code' => 'TR', 'bias' => 'pro_gov', 'language' => 'tr'],
            // TÜRKİYE - Muhalif
            ['name' => 'Cumhuriyet', 'rss_url' => 'https://www.cumhuriyet.com.tr/rss/son_dakika.xml', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'BirGün', 'rss_url' => 'https://www.birgun.net/rss', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'Bianet', 'rss_url' => 'https://bianet.org/bianet/rss', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'Gazete Duvar', 'rss_url' => 'https://www.gazeteduvar.com.tr/feed', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'T24', 'rss_url' => 'https://t24.com.tr/rss', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'Sözcü', 'rss_url' => 'https://www.sozcu.com.tr/rss.xml', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'OdaTV', 'rss_url' => 'https://odatv.com/rss', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'Diken', 'rss_url' => 'https://www.diken.com.tr/feed/', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'Artı Gerçek', 'rss_url' => 'https://artigercek.com/feed', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            ['name' => 'Serbestiyet', 'rss_url' => 'https://serbestiyet.com/feed/', 'country_code' => 'TR', 'bias' => 'opposition', 'language' => 'tr'],
            // ABD - Yandaş
            ['name' => 'Fox News', 'rss_url' => 'https://feeds.foxnews.com/foxnews/world', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Breitbart', 'rss_url' => 'https://feeds.feedburner.com/breitbart', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'NY Post', 'rss_url' => 'https://nypost.com/feed/', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Newsmax', 'rss_url' => 'https://www.newsmax.com/rss/Newsfront/16', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Washington Times', 'rss_url' => 'https://www.washingtontimes.com/rss/headlines/news/world/', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Daily Wire', 'rss_url' => 'https://www.dailywire.com/feeds/rss.xml', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'The Federalist', 'rss_url' => 'https://thefederalist.com/feed/', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'National Review', 'rss_url' => 'https://www.nationalreview.com/feed/', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Daily Caller', 'rss_url' => 'https://dailycaller.com/feed/', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Townhall', 'rss_url' => 'https://townhall.com/rss.xml', 'country_code' => 'US', 'bias' => 'pro_gov', 'language' => 'en'],
            // ABD - Muhalif
            ['name' => 'MSNBC', 'rss_url' => 'https://feeds.nbcnews.com/msnbc/public/news', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'HuffPost', 'rss_url' => 'https://www.huffpost.com/section/world-news/feed', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'The Nation', 'rss_url' => 'https://www.thenation.com/feed/?post_type=article', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Mother Jones', 'rss_url' => 'https://www.motherjones.com/feed/', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Democracy Now', 'rss_url' => 'https://www.democracynow.org/democracynow.rss', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'The Atlantic', 'rss_url' => 'https://www.theatlantic.com/feed/all/', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Vox', 'rss_url' => 'https://www.vox.com/rss/index.xml', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Slate', 'rss_url' => 'https://slate.com/feeds/all.rss', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'The Intercept', 'rss_url' => 'https://theintercept.com/feed/?lang=en', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Common Dreams', 'rss_url' => 'https://www.commondreams.org/rss.xml', 'country_code' => 'US', 'bias' => 'opposition', 'language' => 'en'],
            // İNGİLTERE - Yandaş
            ['name' => 'Daily Mail', 'rss_url' => 'https://www.dailymail.co.uk/articles.rss', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'The Sun', 'rss_url' => 'https://www.thesun.co.uk/feed/', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'GB News', 'rss_url' => 'https://www.gbnews.com/feeds/news.rss', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Daily Express', 'rss_url' => 'https://www.express.co.uk/posts/rss/139/world', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'The Telegraph', 'rss_url' => 'https://www.telegraph.co.uk/rss.xml', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'The Spectator', 'rss_url' => 'https://www.spectator.co.uk/feed', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Daily Star', 'rss_url' => 'https://www.dailystar.co.uk/news/rss.xml', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'City A.M.', 'rss_url' => 'https://www.cityam.com/feed/', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Guido Fawkes', 'rss_url' => 'https://order-order.com/feed/', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'The Critic', 'rss_url' => 'https://thecritic.co.uk/feed/', 'country_code' => 'GB', 'bias' => 'pro_gov', 'language' => 'en'],
            // İNGİLTERE - Muhalif
            ['name' => 'The Guardian', 'rss_url' => 'https://www.theguardian.com/world/rss', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'The Independent', 'rss_url' => 'https://www.independent.co.uk/news/world/rss', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Daily Mirror', 'rss_url' => 'https://www.mirror.co.uk/news/world-news/rss.xml', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'New Statesman', 'rss_url' => 'https://www.newstatesman.com/feed', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'openDemocracy', 'rss_url' => 'https://www.opendemocracy.net/en/rss.xml', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'The Canary', 'rss_url' => 'https://www.thecanary.co/feed/', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Morning Star', 'rss_url' => 'https://morningstaronline.co.uk/rss.xml', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Tribune', 'rss_url' => 'https://tribunemag.co.uk/feed/', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Left Foot Forward', 'rss_url' => 'https://leftfootforward.org/feed/', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'The Conversation UK', 'rss_url' => 'https://theconversation.com/uk/articles.atom', 'country_code' => 'GB', 'bias' => 'opposition', 'language' => 'en'],
            // ALMANYA - Yandaş
            ['name' => 'Bild', 'rss_url' => 'https://www.bild.de/feed/politik.bild.feed.bild.xml', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'Focus Online', 'rss_url' => 'https://rss.focus.de/fol/XML/rss_folnews.xml', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'Welt', 'rss_url' => 'https://www.welt.de/feeds/latest.rss', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'FAZ', 'rss_url' => 'https://www.faz.net/rss/aktuell/', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'Junge Freiheit', 'rss_url' => 'https://www.junge-freiheit.de/feed/', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'n-tv', 'rss_url' => 'https://www.n-tv.de/rss', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'Handelsblatt', 'rss_url' => 'https://www.handelsblatt.com/contentexport/feed/schlagzeilen', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'Cicero', 'rss_url' => 'https://www.cicero.de/feed.rss', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'Tichys Einblick', 'rss_url' => 'https://www.tichyseinblick.de/feed/', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            ['name' => 'Merkur', 'rss_url' => 'https://www.merkur.de/welt/rss.xml', 'country_code' => 'DE', 'bias' => 'pro_gov', 'language' => 'de'],
            // ALMANYA - Muhalif
            ['name' => 'Der Spiegel', 'rss_url' => 'https://www.spiegel.de/schlagzeilen/index.rss', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'Die Zeit', 'rss_url' => 'https://newsfeed.zeit.de/index', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'taz', 'rss_url' => 'https://taz.de/!p4608;rss/', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'Süddeutsche', 'rss_url' => 'https://rss.sueddeutsche.de/rss/Topthemen', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'DW', 'rss_url' => 'https://rss.dw.com/xml/rss-de-all', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'Freitag', 'rss_url' => 'https://www.freitag.de/--xml/rss.xml', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'Neues Deutschland', 'rss_url' => 'https://www.nd-aktuell.de/static/feeds/rss/ndaktuell.rss.xml', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'Jacobin DE', 'rss_url' => 'https://jacobin.de/feed/', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'Kontext', 'rss_url' => 'https://www.kontextwochenzeitung.de/rss.xml', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            ['name' => 'Blätter', 'rss_url' => 'https://www.blaetter.de/rss', 'country_code' => 'DE', 'bias' => 'opposition', 'language' => 'de'],
            // RUSYA - Yandaş
            ['name' => 'RT', 'rss_url' => 'https://www.rt.com/rss/', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'TASS', 'rss_url' => 'https://tass.com/rss/v2.xml', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Sputnik', 'rss_url' => 'https://sputnikglobe.com/export/rss2/world/index.xml', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'RIA Novosti', 'rss_url' => 'https://ria.ru/export/rss2/world/index.xml', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'ru'],
            ['name' => 'Pravda', 'rss_url' => 'https://english.pravda.ru/rss/world.xml', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Russia Beyond', 'rss_url' => 'https://www.rbth.com/rss/', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Rossiyskaya Gazeta', 'rss_url' => 'https://rg.ru/xml/index.xml', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'ru'],
            ['name' => 'Interfax Russia', 'rss_url' => 'https://www.interfax.ru/export/rss.asp', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'ru'],
            ['name' => 'Lenta.ru', 'rss_url' => 'https://lenta.ru/rss/news', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'ru'],
            ['name' => 'Regnum', 'rss_url' => 'https://regnum.ru/news/rss/', 'country_code' => 'RU', 'bias' => 'pro_gov', 'language' => 'ru'],
            // RUSYA - Muhalif
            ['name' => 'Meduza', 'rss_url' => 'https://meduza.io/rss/en/all', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'The Insider', 'rss_url' => 'https://theins.ru/feed', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'iStories', 'rss_url' => 'https://istories.media/feed/', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'ru'],
            ['name' => 'Mediazona', 'rss_url' => 'https://zona.media/rss', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'ru'],
            ['name' => 'Novaya Gazeta', 'rss_url' => 'https://novayagazeta.ru/rss/all.xml', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'ru'],
            ['name' => 'Moscow Times', 'rss_url' => 'https://www.themoscowtimes.com/rss/news', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Bellingcat', 'rss_url' => 'https://www.bellingcat.com/feed/', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Current Time', 'rss_url' => 'https://www.currenttime.tv/api/zmqoiypvq', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'ru'],
            ['name' => 'OpenMedia', 'rss_url' => 'https://openmedia.io/feed/', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'ru'],
            ['name' => 'Kavkaz-Uzel', 'rss_url' => 'https://kavkaz-uzel.eu/rss.xml', 'country_code' => 'RU', 'bias' => 'opposition', 'language' => 'ru'],
            // ÇİN - Yandaş
            ['name' => 'CGTN', 'rss_url' => 'https://www.cgtn.com/subscribe/rss/section/world.xml', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Xinhua', 'rss_url' => 'http://www.xinhuanet.com/english/rss/worldrss.xml', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Global Times', 'rss_url' => 'https://www.globaltimes.cn/rss/world.xml', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => "People's Daily", 'rss_url' => 'http://en.people.cn/rss/90777.xml', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'China Daily', 'rss_url' => 'https://www.chinadaily.com.cn/rss/world_rss.xml', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'China.org.cn', 'rss_url' => 'http://www.china.org.cn/xml/node_7243.xml', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'CRI English', 'rss_url' => 'http://chinaplus.cri.cn/rss/china.xml', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'China Military', 'rss_url' => 'https://eng.chinamil.com.cn/rss/index.xml', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en', 'is_active' => false],
            ['name' => 'Sixth Tone', 'rss_url' => 'https://www.sixthtone.com/rss', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'SCMP', 'rss_url' => 'https://www.scmp.com/rss/91/feed', 'country_code' => 'CN', 'bias' => 'pro_gov', 'language' => 'en'],
            // ÇİN - Muhalif
            ['name' => 'NTD', 'rss_url' => 'https://www.ntd.com/feed', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Radio Free Asia', 'rss_url' => 'https://www.rfa.org/english/RSS', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Epoch Times', 'rss_url' => 'https://www.theepochtimes.com/feed', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'VOA Chinese', 'rss_url' => 'https://www.voachinese.com/api/zmgqiipuoki', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'zh'],
            ['name' => 'RFA Chinese', 'rss_url' => 'https://www.rfa.org/mandarin/RSS', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'zh'],
            ['name' => 'The Diplomat', 'rss_url' => 'https://thediplomat.com/feed/', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'China Digital Times', 'rss_url' => 'https://chinadigitaltimes.net/feed/', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'ChinaFile', 'rss_url' => 'https://www.chinafile.com/rss.xml', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Bitter Winter', 'rss_url' => 'https://bitterwinter.org/feed/', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'SupChina', 'rss_url' => 'https://supchina.com/feed/', 'country_code' => 'CN', 'bias' => 'opposition', 'language' => 'en'],
            // İRAN - Yandaş
            ['name' => 'Press TV', 'rss_url' => 'https://www.presstv.ir/homepages/rss.xml', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'IRNA', 'rss_url' => 'https://en.irna.ir/rss.xml', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Tehran Times', 'rss_url' => 'https://www.tehrantimes.com/rss', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'IFP News', 'rss_url' => 'https://ifpnews.com/feed/', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'ISNA', 'rss_url' => 'https://en.isna.ir/rss.xml', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Financial Tribune', 'rss_url' => 'https://financialtribune.com/feed', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'AhlulBayt News', 'rss_url' => 'https://en.abna24.com/rss/news', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'en', 'is_active' => false],
            ['name' => 'Al-Alam', 'rss_url' => 'https://www.alalam.ir/rss.xml', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'ar'],
            ['name' => 'Javan Online', 'rss_url' => 'https://www.javanonline.ir/rss', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'fa', 'is_active' => false],
            ['name' => 'Hamshahri', 'rss_url' => 'https://www.hamshahrionline.ir/rss.xml', 'country_code' => 'IR', 'bias' => 'pro_gov', 'language' => 'fa', 'is_active' => false],
            // İRAN - Muhalif
            ['name' => 'Iran International', 'rss_url' => 'https://www.iranintl.com/en/rss.xml', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'IranWire', 'rss_url' => 'https://iranwire.com/en/feed/', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Radio Farda', 'rss_url' => 'https://www.radiofarda.com/api/zougoqtiq', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'fa'],
            ['name' => 'Radio Farda EN', 'rss_url' => 'https://www.rferl.org/api/epiypq-hprpiqvii', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Manoto', 'rss_url' => 'https://www.manoto1.com/rss', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'fa', 'is_active' => false],
            ['name' => 'Iran Human Rights', 'rss_url' => 'https://iranhr.net/en/feed/', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'NCRI', 'rss_url' => 'https://www.ncr-iran.org/en/feed/', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Iran Press Watch', 'rss_url' => 'https://iranpresswatch.org/feed/', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Roozonline', 'rss_url' => 'https://www.roozonline.com/english/feed/rss2/index.rss', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Kayhan Life', 'rss_url' => 'https://kayhanlife.com/feed/', 'country_code' => 'IR', 'bias' => 'opposition', 'language' => 'en'],
            // İSRAİL - Yandaş
            ['name' => 'Arutz Sheva', 'rss_url' => 'https://www.israelnationalnews.com/Rss.aspx', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Israel Hayom', 'rss_url' => 'https://www.israelhayom.com/feed/', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Jerusalem Post', 'rss_url' => 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Ynetnews', 'rss_url' => 'https://www.ynetnews.com/Integration/StoryRss2.xml', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Times of Israel', 'rss_url' => 'https://www.timesofisrael.com/feed/', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'i24 News', 'rss_url' => 'https://www.i24news.tv/en/rss', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Maariv', 'rss_url' => 'https://www.maariv.co.il/rss/rssfeed.aspx', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'he'],
            ['name' => 'Walla News', 'rss_url' => 'https://rss.walla.co.il/feed/1', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'he'],
            ['name' => 'The Algemeiner', 'rss_url' => 'https://www.algemeiner.com/feed/', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Jewish Press', 'rss_url' => 'https://www.jewishpress.com/feed/', 'country_code' => 'IL', 'bias' => 'pro_gov', 'language' => 'en'],
            // İSRAİL - Muhalif
            ['name' => 'Haaretz', 'rss_url' => 'https://www.haaretz.com/cmlink/1.628765', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => '+972 Magazine', 'rss_url' => 'https://www.972mag.com/feed/', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Local Call', 'rss_url' => 'https://localcall.co.il/feed/', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'en', 'is_active' => false],
            ['name' => 'Mekomit', 'rss_url' => 'https://www.mekomit.co.il/feed/', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'he'],
            ['name' => 'Siha Mekomit', 'rss_url' => 'https://mekomit.co.il/feed/', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'he'],
            ['name' => 'The Seventh Eye', 'rss_url' => 'https://www.the7eye.org.il/feed', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'he'],
            ['name' => 'Mondoweiss', 'rss_url' => 'https://mondoweiss.net/feed/', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Middle East Monitor', 'rss_url' => 'https://www.middleeastmonitor.com/feed/', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Haokets', 'rss_url' => 'https://www.haokets.org/feed/', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'he'],
            ['name' => 'Adalah', 'rss_url' => 'https://www.adalah.org/en/rss/updates', 'country_code' => 'IL', 'bias' => 'opposition', 'language' => 'en'],
            // SUUDİ ARABİSTAN - Yandaş
            ['name' => 'Saudi Gazette', 'rss_url' => 'https://saudigazette.com.sa/rss.xml', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Arab News', 'rss_url' => 'https://www.arabnews.com/rss.xml', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Al Arabiya', 'rss_url' => 'https://english.alarabiya.net/tools/rss', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'SPA', 'rss_url' => 'https://www.spa.gov.sa/rss/rss_en.xml', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Asharq Al-Awsat', 'rss_url' => 'https://english.aawsat.com/rss.xml', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Al Riyadh', 'rss_url' => 'http://www.alriyadh.com/rss/', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'ar'],
            ['name' => 'Okaz', 'rss_url' => 'https://www.okaz.com.sa/rss', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'ar'],
            ['name' => 'Gulf News', 'rss_url' => 'https://gulfnews.com/rss', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Al Watan SA', 'rss_url' => 'https://alwatan.com.sa/rss', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'ar'],
            ['name' => 'Saudi 24 News', 'rss_url' => 'https://www.saudi24news.com/feed/', 'country_code' => 'SA', 'bias' => 'pro_gov', 'language' => 'en'],
            // SUUDİ ARABİSTAN - Muhalif
            ['name' => 'Alqst', 'rss_url' => 'https://alqst.org/feed', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'DAWN', 'rss_url' => 'https://dawnmena.org/feed/', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Middle East Eye', 'rss_url' => 'https://www.middleeasteye.net/rss', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Al-Monitor', 'rss_url' => 'https://www.al-monitor.com/rss', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Arabi21', 'rss_url' => 'https://arabi21.com/rss.xml', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'ar'],
            ['name' => 'Al-Araby Al-Jadeed', 'rss_url' => 'https://www.alaraby.co.uk/feed', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Raseef22', 'rss_url' => 'https://raseef22.net/feed/', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'ar'],
            ['name' => 'Daraj Media', 'rss_url' => 'https://daraj.media/feed/', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'ar'],
            ['name' => 'HRW MENA', 'rss_url' => 'https://www.hrw.org/rss/news/middle-east-north-africa', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Amnesty MENA', 'rss_url' => 'https://www.amnesty.org/en/location/middle-east-and-north-africa/rss/', 'country_code' => 'SA', 'bias' => 'opposition', 'language' => 'en'],
            // MISIR - Yandaş
            ['name' => 'Al-Ahram', 'rss_url' => 'https://english.ahram.org.eg/UI/Front/ContentRss.aspx?secID=1', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Egypt Today', 'rss_url' => 'https://www.egypttoday.com/rss.xml', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Daily News Egypt', 'rss_url' => 'https://www.dailynewsegypt.com/feed/', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Akhbar al-Youm', 'rss_url' => 'https://akhbarelyom.com/rss.xml', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'ar'],
            ['name' => 'Al-Masry Al-Youm', 'rss_url' => 'https://www.egyptindependent.com/feed/', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'en'],
            ['name' => 'Al-Shorouk', 'rss_url' => 'https://www.shorouknews.com/rss.xml', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'ar'],
            ['name' => 'Youm7', 'rss_url' => 'https://www.youm7.com/rss.xml', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'ar'],
            ['name' => 'Al-Watan Egypt', 'rss_url' => 'https://www.elwatannews.com/rss.xml', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'ar'],
            ['name' => 'Sada El-Balad', 'rss_url' => 'https://www.sada-elbalad.com/rss', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'ar', 'is_active' => false],
            ['name' => 'Al-Ahram Weekly', 'rss_url' => 'https://english.ahram.org.eg/UI/Front/ContentRss.aspx?secID=17', 'country_code' => 'EG', 'bias' => 'pro_gov', 'language' => 'en'],
            // MISIR - Muhalif
            ['name' => 'Mada Masr', 'rss_url' => 'https://www.madamasr.com/en/feed/', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'en'],
            ['name' => 'Al-Manassa', 'rss_url' => 'https://al-manassa.com/feed/', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar'],
            ['name' => 'Daraj', 'rss_url' => 'https://daraj.com/feed/', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar'],
            ['name' => 'Noon Post', 'rss_url' => 'https://www.noonpost.com/feed/', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar'],
            ['name' => 'Egypt Wide', 'rss_url' => 'https://egyptwide.com/feed/', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar', 'is_active' => false],
            ['name' => 'HuffPost Arabic', 'rss_url' => 'https://www.huffpostarabi.com/feeds/index.xml', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar', 'is_active' => false],
            ['name' => 'Raseef22 EG', 'rss_url' => 'https://raseef22.net/feed/', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar'],
            ['name' => 'Al-Mashhad', 'rss_url' => 'https://almashhad.net/feed/', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar', 'is_active' => false],
            ['name' => 'Masr Al-Arabia', 'rss_url' => 'https://www.masralarabia.net/feed/', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar', 'is_active' => false],
            ['name' => 'El-Fagr', 'rss_url' => 'https://www.elfagr.com/rss.xml', 'country_code' => 'EG', 'bias' => 'opposition', 'language' => 'ar'],
        ];

        foreach ($sources as $source) {
            $isActive = $source['is_active'] ?? true;
            unset($source['is_active']);
            Source::updateOrCreate(
                ['name' => $source['name'], 'country_code' => $source['country_code']],
                array_merge($source, ['is_active' => $isActive])
            );
        }

        $this->command->info('Seeded ' . count($sources) . ' sources.');
    }
}
